### ISSUE TITLE
Tag Edit

### ISSUE THREAD

**Issue by rehankalu** [GPropersi/urls4irl#25]
Tags should be able to be edited

**Comment by GPropersi** [comment]
Thoughts on this from database perspective - either find the newly edited tag in the tag table, or create it and add it to the tag table. This is opposed to removing the old tag (one the user is editing away from) from the database.

Example:
User incorrectly adds 'Reh' as a tag.

User meant to add 'Rehan' as a tag, so user edits the tag.

'Reh' still is stored as a potential tag and has its own unique ID regardless. However, 'Rehan' is now associated with the URL instead of 'Reh'.

**Comment by GPropersi** [comment]
Added tag modification #65
